//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public Good()
        {
            this.GoodsInCells = new HashSet<GoodsInCell>();
            this.UserCarts = new HashSet<UserCart>();
        }
    
        public int Id { get; set; }
        public int ConsignmentId { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public System.DateTime AddingDate { get; set; }
    
        public virtual Consignment Consignment { get; set; }
        public virtual ICollection<GoodsInCell> GoodsInCells { get; set; }
        public virtual ICollection<UserCart> UserCarts { get; set; }
    }
}
