//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LoginedUsers = new HashSet<LoginedUser>();
            this.UserCarts = new HashSet<UserCart>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLoginedDate { get; set; }
    
        public virtual ICollection<LoginedUser> LoginedUsers { get; set; }
        public virtual ICollection<UserCart> UserCarts { get; set; }
    }
}
